---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r,message=FALSE,warnings=FALSE}
library(tidyverse)
data<-read_csv('activity.csv')
```



## What is mean total number of steps taken per day?
```{r Total steps by day}
data_total_day<-data %>% 
    na.omit %>% 
    group_by(date) %>% 
    summarise(Total=sum(steps))
data_total_day %>% head(10) %>% knitr::kable()
```
```{r Histogram}
ggplot(data_total_day,aes(x=Total))+
    geom_histogram(bins = 10,fill='skyblue',col='blue')+
    labs(title = 'Histogram')+
    xlab('Total steps by day')+
    ylab('N')

```
```{r Mean and Median}
data_total_day %>% 
    summarise(Mean=mean(Total),Median=median(Total)) %>% 
    knitr::kable()
```
    






## What is the average daily activity pattern?
```{r Time Series Plot}

data_interval<-data %>% 
    na.omit %>% 
    group_by(interval) %>% 
    summarise(Mean=mean(steps))
data_interval %>% ggplot(aes(x=interval,y=Mean))+
    geom_line(col='blue')+
    labs(title='TIME SERIES FOR AVERAGE DAILY ACTIVITY PATTERN',
         subtitle='Five-minutes intervals')+
    xlab('Intervals')+
    ylab('Average daily activity pattern')
    
```
```{r Max value}
data_interval %>% summarise(interval=interval[which.max(Mean)]) %>% knitr::kable()
```



## Imputing missing values
```{r Total Nas}
paste('There are',sum(is.na(data)), 'missing values')
```
```{r Replace Nas}
data_2=data
data_interval<-data %>% 
    na.omit %>% 
    group_by(interval) %>% 
    summarise(Mean=mean(steps))
for(i in 1:nrow(data)){
    for(j in 1:nrow(data_interval)){
     if(is.na(data[i,1])==TRUE){
         if(data[i,3]==data_interval[j,1]){
             data_2[i,1]=data_interval[j,2]
         }
     }}}
head(data_2) %>% knitr::kable()
```


```{r Histogram 2}
data_total<-data_2 %>% 
    group_by(date_2) %>% 
    summarise(Total=sum(steps))
ggplot(data_total,aes(x=Total))+
    geom_histogram(bins = 10,fill='skyblue',col='blue')+
    labs(title = 'Histogram')+
    xlab('Total steps by day')+
    ylab('N')

```
```{r Mean & Median 2}
data_total %>% 
    summarise(Mean=mean(Total),Median=median(Total)) %>% 
    knitr::kable()

```





## Are there differences in activity patterns between weekdays and weekends?
```{r Diff btw week and weekends}
data_wk<-data %>% 
    mutate(day=format(date,'%A'))
data_wk_1=data_wk %>% 
    mutate(Factor=ifelse(data_wk$day %in%c('sábado','domingo'),
                         'weekends','weekdays'))
data_wk_1 %>% head() %>% knitr::kable()

```
```{r Time Series Plot 2}
data_wk_2<-data_wk_1 %>% group_by(interval,Factor) %>% 
    summarise(total=mean(steps,na.rm=TRUE))
ggplot(data_wk_2,aes(x=interval,y=total))+
    geom_line(col='blue')+
    theme_minimal()+
    facet_grid(vars(Factor))+
    labs(title='TIME SERIES')



```

